package main;

import java.nio.file.Files;
import java.nio.file.Paths;

import json.interpreter.JsonGenerator;

public abstract class JsonPojo {
	public static void main(String[] args) throws Exception {
//		String input = "{\r\n"
//				+ "    \"ticket_id\" : \"200715173538\",\r\n"
//				+ "    \"exam_start_time\" : 1594809338,\r\n"
//				+ "    \"exam_ending_time\" : 1602556004,\r\n"
//				+ "    \"date\" : \"2020-07-15\",\r\n"
//				+ "    \"result\" : {\r\n"
//				+ "        \"medical_history\" : {\r\n"
//				+ "            \"ocular_history\" : {\r\n"
//				+ "                \"refractive_error\" : [ \r\n"
//				+ "                    \"myopia\", \r\n"
//				+ "                    \"astigmatism\"\r\n"
//				+ "                ],\r\n"
//				+ "                \"surgery\" : [ \r\n"
//				+ "                    \"none\"\r\n"
//				+ "                ],\r\n"
//				+ "                \"od\" : {\r\n"
//				+ "                    \"cataract\" : \"no\",\r\n"
//				+ "                    \"glaucoma\" : \"no\",\r\n"
//				+ "                    \"retinal_diseases\" : \"no\",\r\n"
//				+ "                    \"uveitis\" : \"no\"\r\n"
//				+ "                },\r\n"
//				+ "                \"os\" : {\r\n"
//				+ "                    \"cataract\" : \"no\",\r\n"
//				+ "                    \"glaucoma\" : \"no\",\r\n"
//				+ "                    \"retinal_diseases\" : \"no\",\r\n"
//				+ "                    \"uveitis\" : \"no\"\r\n"
//				+ "                }\r\n"
//				+ "            },\r\n"
//				+ "            \"systemic_condition\" : {\r\n"
//				+ "                \"diabetes\" : \"no\",\r\n"
//				+ "                \"diabetes_year\" : \"\",\r\n"
//				+ "                \"hypertension\" : \"no\",\r\n"
//				+ "                \"hypertension_year\" : \"\",\r\n"
//				+ "                \"hypotension\" : \"no\",\r\n"
//				+ "                \"hypotension_year\" : \"\",\r\n"
//				+ "                \"steroid_use\" : \"no\"\r\n"
//				+ "            },\r\n"
//				+ "            \"fmh\" : {\r\n"
//				+ "                \"cataract\" : \"no\",\r\n"
//				+ "                \"glaucoma\" : \"no\",\r\n"
//				+ "                \"retinal\" : \"no\",\r\n"
//				+ "                \"uveitis\" : \"no\",\r\n"
//				+ "                \"diabetes\" : \"no\",\r\n"
//				+ "                \"hypertension\" : [ \r\n"
//				+ "                    \"parent\"\r\n"
//				+ "                ],\r\n"
//				+ "                \"hypotension\" : \"no\",\r\n"
//				+ "                \"parents_myopia\" : \"mother\"\r\n"
//				+ "            },\r\n"
//				+ "            \"blur_vision_specification\" : {\r\n"
//				+ "                \"eyeside\" : null,\r\n"
//				+ "                \"severity\" : null,\r\n"
//				+ "                \"onset\" : null,\r\n"
//				+ "                \"duration\" : null,\r\n"
//				+ "                \"pain\" : null\r\n"
//				+ "            },\r\n"
//				+ "            \"pain_specification\" : {\r\n"
//				+ "                \"eyeside\" : null,\r\n"
//				+ "                \"severity\" : null,\r\n"
//				+ "                \"onset\" : null,\r\n"
//				+ "                \"duration\" : null\r\n"
//				+ "            },\r\n"
//				+ "            \"floater_specification\" : {\r\n"
//				+ "                \"eyeside\" : null,\r\n"
//				+ "                \"severity\" : null,\r\n"
//				+ "                \"onset\" : null,\r\n"
//				+ "                \"duration\" : null\r\n"
//				+ "            },\r\n"
//				+ "            \"redness_specification\" : {\r\n"
//				+ "                \"eyeside\" : null,\r\n"
//				+ "                \"severity\" : null,\r\n"
//				+ "                \"onset\" : null,\r\n"
//				+ "                \"duration\" : null\r\n"
//				+ "            },\r\n"
//				+ "            \"social_history\" : {\r\n"
//				+ "                \"smoker\" : \"no\",\r\n"
//				+ "                \"smoking_duration\" : \"\",\r\n"
//				+ "                \"smoking_amount\" : \"\",\r\n"
//				+ "                \"alcohol_user\" : \"past\",\r\n"
//				+ "                \"alcohol_frequence\" : \"1\",\r\n"
//				+ "                \"smart_device_usage\" : \"12\"\r\n"
//				+ "            },\r\n"
//				+ "            \"vision_correction\" : {\r\n"
//				+ "                \"glass_wearer\" : \"yes\",\r\n"
//				+ "                \"contact_lens_wearer\" : \"no\",\r\n"
//				+ "                \"contact_lens_wear_frequence\" : \"\",\r\n"
//				+ "                \"last_checkup\" : \"\",\r\n"
//				+ "                \"shop_glass\" : null,\r\n"
//				+ "                \"current_glass_prescription\" : {\r\n"
//				+ "                    \"od\" : {\r\n"
//				+ "                        \"sph\" : \"\",\r\n"
//				+ "                        \"axs\" : \"\",\r\n"
//				+ "                        \"cyl\" : \"\",\r\n"
//				+ "                        \"va\" : \"\",\r\n"
//				+ "                        \"add\" : \"\"\r\n"
//				+ "                    },\r\n"
//				+ "                    \"os\" : {\r\n"
//				+ "                        \"sph\" : \"\",\r\n"
//				+ "                        \"axs\" : \"\",\r\n"
//				+ "                        \"cyl\" : \"\",\r\n"
//				+ "                        \"va\" : \"\",\r\n"
//				+ "                        \"add\" : \"\"\r\n"
//				+ "                    },\r\n"
//				+ "                    \"pd\" : \"\",\r\n"
//				+ "                    \"distant_glass\" : {\r\n"
//				+ "                        \"pd\" : \"65\",\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"sph\" : \"-0.75\",\r\n"
//				+ "                            \"axs\" : \"\",\r\n"
//				+ "                            \"cyl\" : \"\",\r\n"
//				+ "                            \"va\" : \"10/10\"\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"sph\" : \"plano\",\r\n"
//				+ "                            \"axs\" : \"5\",\r\n"
//				+ "                            \"cyl\" : \"-0.75\",\r\n"
//				+ "                            \"va\" : \"10/10\"\r\n"
//				+ "                        },\r\n"
//				+ "                        \"shop_glass\" : \"other\"\r\n"
//				+ "                    },\r\n"
//				+ "                    \"near_glass\" : {\r\n"
//				+ "                        \"pd\" : \"63\",\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"sph\" : \"+1.75D\",\r\n"
//				+ "                            \"axs\" : \"\",\r\n"
//				+ "                            \"cyl\" : \"\",\r\n"
//				+ "                            \"nva\" : \"G5@35-40\"\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"sph\" : \"+2.50\",\r\n"
//				+ "                            \"axs\" : \"5\",\r\n"
//				+ "                            \"cyl\" : \"-0.75\",\r\n"
//				+ "                            \"nva\" : \"G5@35-40\"\r\n"
//				+ "                        },\r\n"
//				+ "                        \"shop_glass\" : \"ct\"\r\n"
//				+ "                    }\r\n"
//				+ "                },\r\n"
//				+ "                \"shop_lens\" : null,\r\n"
//				+ "                \"current_lens_prescription\" : {\r\n"
//				+ "                    \"od\" : {\r\n"
//				+ "                        \"sph\" : \"\",\r\n"
//				+ "                        \"axs\" : \"\",\r\n"
//				+ "                        \"cyl\" : \"\"\r\n"
//				+ "                    },\r\n"
//				+ "                    \"os\" : {\r\n"
//				+ "                        \"sph\" : \"\",\r\n"
//				+ "                        \"axs\" : \"\",\r\n"
//				+ "                        \"cyl\" : \"\"\r\n"
//				+ "                    },\r\n"
//				+ "                    \"pd\" : \"\",\r\n"
//				+ "                    \"add\" : \"\"\r\n"
//				+ "                }\r\n"
//				+ "            },\r\n"
//				+ "            \"visual_demand\" : {\r\n"
//				+ "                \"job\" : \"AI developer\",\r\n"
//				+ "                \"demand\" : \"near\"\r\n"
//				+ "            },\r\n"
//				+ "            \"start_time\" : \"1605523559\",\r\n"
//				+ "            \"end_time\" : \"1605523571\",\r\n"
//				+ "            \"perform_by\" : \"user_id\",\r\n"
//				+ "            \"chief_complaint\" : \"Redness specification (d? m?t)\",\r\n"
//				+ "            \"other_complaints\" : null,\r\n"
//				+ "            \"medication_in_use\" : null\r\n"
//				+ "        },\r\n"
//				+ "        \"visual_acuity\" : {\r\n"
//				+ "            \"start_time\" : 1601387344,\r\n"
//				+ "            \"end_time\" : 1601387360,\r\n"
//				+ "            \"perform_by\" : \"User-id-1\",\r\n"
//				+ "            \"near_vision\" : {\r\n"
//				+ "                \"od\" : null,\r\n"
//				+ "                \"os\" : null\r\n"
//				+ "            },\r\n"
//				+ "            \"distant_vision\" : {\r\n"
//				+ "                \"dataType\" : \"tp\",\r\n"
//				+ "                \"sc\" : {\r\n"
//				+ "                    \"od\" : \"7/10\",\r\n"
//				+ "                    \"os\" : \"9/10\",\r\n"
//				+ "                    \"ou\" : null\r\n"
//				+ "                },\r\n"
//				+ "                \"cc\" : {\r\n"
//				+ "                    \"od\" : null,\r\n"
//				+ "                    \"os\" : null,\r\n"
//				+ "                    \"ou\" : null\r\n"
//				+ "                }\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"cover_test\" : {\r\n"
//				+ "            \"type\" : \"tropia\",\r\n"
//				+ "            \"without_spec\" : [],\r\n"
//				+ "            \"with_old_spec\" : {\r\n"
//				+ "                \"distant\" : {\r\n"
//				+ "                    \"ortho\" : {\r\n"
//				+ "                        \"type\" : \"exo\",\r\n"
//				+ "                        \"prism_diopter\" : null\r\n"
//				+ "                    }\r\n"
//				+ "                },\r\n"
//				+ "                \"near\" : {\r\n"
//				+ "                    \"od\" : null,\r\n"
//				+ "                    \"os\" : {\r\n"
//				+ "                        \"type\" : \"eso\",\r\n"
//				+ "                        \"prism_diopter\" : \"13123\",\r\n"
//				+ "                        \"change\" : null\r\n"
//				+ "                    },\r\n"
//				+ "                    \"alternative\" : null\r\n"
//				+ "                }\r\n"
//				+ "            },\r\n"
//				+ "            \"with_new_spec\" : [],\r\n"
//				+ "            \"after_dilation\" : [],\r\n"
//				+ "            \"start_time\" : null,\r\n"
//				+ "            \"end_time\" : 1602561065,\r\n"
//				+ "            \"perform_by\" : \"user-id\"\r\n"
//				+ "        },\r\n"
//				+ "        \"visual_field\" : {\r\n"
//				+ "            \"start_time\" : 1601387766,\r\n"
//				+ "            \"end_time\" : 1601387772,\r\n"
//				+ "            \"perform_by\" : \"user-id\",\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"status\" : \"restricted\",\r\n"
//				+ "                \"quadrant\" : [ \r\n"
//				+ "                    \"Superiotemporal\"\r\n"
//				+ "                ]\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"status\" : \"restricted\",\r\n"
//				+ "                \"quadrant\" : [ \r\n"
//				+ "                    \"Inferiotemporal\", \r\n"
//				+ "                    \"Inferionasal\"\r\n"
//				+ "                ]\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"aa\" : {\r\n"
//				+ "            \"start_time\" : 1601387678,\r\n"
//				+ "            \"end_time\" : 1601387683,\r\n"
//				+ "            \"perform_by\" : \"user-id\",\r\n"
//				+ "            \"method\" : \"pu\",\r\n"
//				+ "            \"od\" : \"12\",\r\n"
//				+ "            \"os\" : \"10\"\r\n"
//				+ "        },\r\n"
//				+ "        \"ocular_motility\" : {\r\n"
//				+ "            \"start_time\" : null,\r\n"
//				+ "            \"end_time\" : 1601388185,\r\n"
//				+ "            \"perform_by\" : \"user_login\",\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"IX\" : \"SAFE\"\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"IX\" : \"SAFE\"\r\n"
//				+ "            },\r\n"
//				+ "            \"other_conditions\" : []\r\n"
//				+ "        },\r\n"
//				+ "        \"stereo\" : {\r\n"
//				+ "            \"start_time\" : 1601387747,\r\n"
//				+ "            \"end_time\" : 1601387755,\r\n"
//				+ "            \"perform_by\" : \"user-id\",\r\n"
//				+ "            \"global_text\" : \"100\",\r\n"
//				+ "            \"contour_text\" : \"25\"\r\n"
//				+ "        },\r\n"
//				+ "        \"color_vision\" : {\r\n"
//				+ "            \"start_time\" : 1601387801,\r\n"
//				+ "            \"end_time\" : 1601387808,\r\n"
//				+ "            \"perform_by\" : \"user-id\",\r\n"
//				+ "            \"method\" : \"ishihara\",\r\n"
//				+ "            \"od\" : \"bình thu?ng\",\r\n"
//				+ "            \"os\" : \"8/10\"\r\n"
//				+ "        },\r\n"
//				+ "        \"pupillary\" : {\r\n"
//				+ "            \"start_time\" : 1601387830,\r\n"
//				+ "            \"end_time\" : 1601387831,\r\n"
//				+ "            \"perform_by\" : \"user-id\",\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"status\" : \"abnormal\",\r\n"
//				+ "                \"p\" : null,\r\n"
//				+ "                \"e\" : null,\r\n"
//				+ "                \"re\" : null,\r\n"
//				+ "                \"ro\" : null,\r\n"
//				+ "                \"l\" : null,\r\n"
//				+ "                \"a\" : null,\r\n"
//				+ "                \"mg\" : {\r\n"
//				+ "                    \"status\" : \"negative\",\r\n"
//				+ "                    \"degree\" : \"0\"\r\n"
//				+ "                }\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"status\" : \"abnormal\",\r\n"
//				+ "                \"p\" : null,\r\n"
//				+ "                \"e\" : null,\r\n"
//				+ "                \"re\" : null,\r\n"
//				+ "                \"ro\" : null,\r\n"
//				+ "                \"l\" : null,\r\n"
//				+ "                \"a\" : null,\r\n"
//				+ "                \"mg\" : {\r\n"
//				+ "                    \"status\" : \"negative\",\r\n"
//				+ "                    \"degree\" : \"0\"\r\n"
//				+ "                }\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"objective_refraction\" : {\r\n"
//				+ "            \"start_time\" : \"1601387499\",\r\n"
//				+ "            \"end_time\" : \"1601387527\",\r\n"
//				+ "            \"perform_by\" : \"user_id\",\r\n"
//				+ "            \"pd\" : \"63\",\r\n"
//				+ "            \"dry_rx\" : {\r\n"
//				+ "                \"od\" : {\r\n"
//				+ "                    \"sph\" : \"\",\r\n"
//				+ "                    \"axs\" : \"\",\r\n"
//				+ "                    \"cyl\" : \"\"\r\n"
//				+ "                },\r\n"
//				+ "                \"os\" : {\r\n"
//				+ "                    \"sph\" : \"\",\r\n"
//				+ "                    \"axs\" : \"\",\r\n"
//				+ "                    \"cyl\" : \"\"\r\n"
//				+ "                },\r\n"
//				+ "                \"add\" : \"\"\r\n"
//				+ "            },\r\n"
//				+ "            \"wet_rx\" : {\r\n"
//				+ "                \"first_drop_time\" : \"\",\r\n"
//				+ "                \"second_drop_time\" : \"\",\r\n"
//				+ "                \"od\" : {\r\n"
//				+ "                    \"sph\" : \"\",\r\n"
//				+ "                    \"axs\" : \"\",\r\n"
//				+ "                    \"cyl\" : \"\"\r\n"
//				+ "                },\r\n"
//				+ "                \"os\" : {\r\n"
//				+ "                    \"sph\" : \"\",\r\n"
//				+ "                    \"axs\" : \"\",\r\n"
//				+ "                    \"cyl\" : \"\"\r\n"
//				+ "                },\r\n"
//				+ "                \"add\" : \"\"\r\n"
//				+ "            },\r\n"
//				+ "            \"iop\" : {\r\n"
//				+ "                \"od\" : \"11\",\r\n"
//				+ "                \"os\" : \"12\"\r\n"
//				+ "            },\r\n"
//				+ "            \"URL_auto_dry\" : \"200715173538_dry_autorefractor.png\",\r\n"
//				+ "            \"URL_tonometer\" : \"200715173538_wet_autorefractor.png\"\r\n"
//				+ "        },\r\n"
//				+ "        \"subjective_refraction\" : {\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"sph\" : \"-0.75\",\r\n"
//				+ "                \"axs\" : \"\",\r\n"
//				+ "                \"cyl\" : \"\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"g\" : \"G6\",\r\n"
//				+ "                \"range\" : \"20-25\"\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"sph\" : \"plano\",\r\n"
//				+ "                \"axs\" : \"180\",\r\n"
//				+ "                \"cyl\" : \"-0.75\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"g\" : \"G5\",\r\n"
//				+ "                \"range\" : \"35-40\"\r\n"
//				+ "            },\r\n"
//				+ "            \"start_time\" : \"1601542562\",\r\n"
//				+ "            \"end_time\" : \"1601542563\",\r\n"
//				+ "            \"perform_by\" : \"user_id\",\r\n"
//				+ "            \"bcva\" : \"10/10\"\r\n"
//				+ "        },\r\n"
//				+ "        \"glass_prescription\" : {\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"sph\" : \"-0.75\",\r\n"
//				+ "                \"axs\" : \"\",\r\n"
//				+ "                \"cyl\" : \"\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"g\" : \"G6\",\r\n"
//				+ "                \"range\" : \"20-25\"\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"sph\" : \"plano\",\r\n"
//				+ "                \"axs\" : \"180\",\r\n"
//				+ "                \"cyl\" : \"-0.75\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"g\" : \"G5\",\r\n"
//				+ "                \"range\" : \"35-40\"\r\n"
//				+ "            },\r\n"
//				+ "            \"start_time\" : \"1601873112\",\r\n"
//				+ "            \"end_time\" : \"1601873152\",\r\n"
//				+ "            \"perform_by\" : \"user_id\",\r\n"
//				+ "            \"bcva\" : \"\",\r\n"
//				+ "            \"glass_type\" : \"progressive glass\",\r\n"
//				+ "            \"glass_description\" : \"\",\r\n"
//				+ "            \"progressive_type\" : \"PALs\",\r\n"
//				+ "            \"glass_indication\" : null,\r\n"
//				+ "            \"note\" : \"\"\r\n"
//				+ "        },\r\n"
//				+ "        \"ocular_health\" : {\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"1\" : \"normal\",\r\n"
//				+ "                \"3\" : [ \r\n"
//				+ "                    {\r\n"
//				+ "                        \"assessment_detail\" : \"3\",\r\n"
//				+ "                        \"assessment_detail_enum\" : \"420\",\r\n"
//				+ "                        \"description\" : \"K?t m?c - B?t thu?ng k?t m?c - Khô m?t\"\r\n"
//				+ "                    }\r\n"
//				+ "                ],\r\n"
//				+ "                \"4\" : \"normal\",\r\n"
//				+ "                \"6\" : \"normal\",\r\n"
//				+ "                \"7\" : \"normal\",\r\n"
//				+ "                \"9\" : \"normal\",\r\n"
//				+ "                \"2\" : [ \r\n"
//				+ "                    {\r\n"
//				+ "                        \"assessment_detail\" : \"189\",\r\n"
//				+ "                        \"assessment_detail_enum\" : \"412\",\r\n"
//				+ "                        \"description\" : \"Mí m?t - MGD - Stage 1\"\r\n"
//				+ "                    }\r\n"
//				+ "                ]\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"1\" : \"normal\",\r\n"
//				+ "                \"2\" : [ \r\n"
//				+ "                    {\r\n"
//				+ "                        \"assessment_detail\" : \"189\",\r\n"
//				+ "                        \"assessment_detail_enum\" : \"413\",\r\n"
//				+ "                        \"description\" : \"Mí m?t - MGD - Stage 2\"\r\n"
//				+ "                    }\r\n"
//				+ "                ],\r\n"
//				+ "                \"4\" : \"normal\",\r\n"
//				+ "                \"6\" : \"normal\",\r\n"
//				+ "                \"7\" : \"normal\",\r\n"
//				+ "                \"9\" : \"normal\",\r\n"
//				+ "                \"3\" : [ \r\n"
//				+ "                    {\r\n"
//				+ "                        \"assessment_detail\" : \"3\",\r\n"
//				+ "                        \"assessment_detail_enum\" : \"176\",\r\n"
//				+ "                        \"description\" : \"K?t m?c - B?t thu?ng k?t m?c - Nhú\"\r\n"
//				+ "                    }\r\n"
//				+ "                ]\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"npc\" : {\r\n"
//				+ "            \"start_time\" : 1601387758,\r\n"
//				+ "            \"end_time\" : 1601387763,\r\n"
//				+ "            \"perform_by\" : \"user-id\",\r\n"
//				+ "            \"break\" : \"5\",\r\n"
//				+ "            \"recover\" : \"7\",\r\n"
//				+ "            \"nose\" : \"no\"\r\n"
//				+ "        },\r\n"
//				+ "        \"note\" : null,\r\n"
//				+ "        \"contact_lens\" : {\r\n"
//				+ "            \"fitting\" : {\r\n"
//				+ "                \"order\" : {\r\n"
//				+ "                    \"len_detail\" : {\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"diameter\" : null,\r\n"
//				+ "                            \"code\" : null\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"diameter\" : null,\r\n"
//				+ "                            \"code\" : null\r\n"
//				+ "                        }\r\n"
//				+ "                    },\r\n"
//				+ "                    \"movement\" : {\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"distant\" : null\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"distant\" : null\r\n"
//				+ "                        }\r\n"
//				+ "                    },\r\n"
//				+ "                    \"fluorescein\" : {\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"center\" : null\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"center\" : null\r\n"
//				+ "                        },\r\n"
//				+ "                        \"note\" : null\r\n"
//				+ "                    },\r\n"
//				+ "                    \"va_cls\" : {\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"va_with_cls\" : null,\r\n"
//				+ "                            \"over_ref\" : {\r\n"
//				+ "                                \"sph\" : null,\r\n"
//				+ "                                \"cyl\" : null,\r\n"
//				+ "                                \"axs\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"va_without_cls\" : null\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"va_with_cls\" : null,\r\n"
//				+ "                            \"over_ref\" : {\r\n"
//				+ "                                \"sph\" : null,\r\n"
//				+ "                                \"cyl\" : null,\r\n"
//				+ "                                \"axs\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"va_without_cls\" : null\r\n"
//				+ "                        }\r\n"
//				+ "                    },\r\n"
//				+ "                    \"order_lens\" : {\r\n"
//				+ "                        \"od\" : {\r\n"
//				+ "                            \"brand\" : \"fargo\",\r\n"
//				+ "                            \"type\" : \"standard\",\r\n"
//				+ "                            \"diameter\" : \"5\",\r\n"
//				+ "                            \"code\" : \"55\"\r\n"
//				+ "                        },\r\n"
//				+ "                        \"os\" : {\r\n"
//				+ "                            \"brand\" : \"gov\",\r\n"
//				+ "                            \"type\" : \"extended\",\r\n"
//				+ "                            \"diameter\" : \"2\",\r\n"
//				+ "                            \"code\" : \"63\"\r\n"
//				+ "                        }\r\n"
//				+ "                    }\r\n"
//				+ "                },\r\n"
//				+ "                \"trial\" : {\r\n"
//				+ "                    \"1\" : {\r\n"
//				+ "                        \"len_detail\" : {\r\n"
//				+ "                            \"od\" : {\r\n"
//				+ "                                \"diameter\" : null,\r\n"
//				+ "                                \"code\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"os\" : {\r\n"
//				+ "                                \"diameter\" : null,\r\n"
//				+ "                                \"code\" : null\r\n"
//				+ "                            }\r\n"
//				+ "                        },\r\n"
//				+ "                        \"movement\" : {\r\n"
//				+ "                            \"od\" : {\r\n"
//				+ "                                \"distant\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"os\" : {\r\n"
//				+ "                                \"distant\" : null\r\n"
//				+ "                            }\r\n"
//				+ "                        },\r\n"
//				+ "                        \"fluorescein\" : {\r\n"
//				+ "                            \"od\" : {\r\n"
//				+ "                                \"center\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"os\" : {\r\n"
//				+ "                                \"center\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"note\" : null\r\n"
//				+ "                        },\r\n"
//				+ "                        \"va_cls\" : {\r\n"
//				+ "                            \"od\" : {\r\n"
//				+ "                                \"va_with_cls\" : null,\r\n"
//				+ "                                \"over_ref\" : {\r\n"
//				+ "                                    \"sph\" : null,\r\n"
//				+ "                                    \"cyl\" : null,\r\n"
//				+ "                                    \"axs\" : null\r\n"
//				+ "                                },\r\n"
//				+ "                                \"va_without_cls\" : null\r\n"
//				+ "                            },\r\n"
//				+ "                            \"os\" : {\r\n"
//				+ "                                \"va_with_cls\" : null,\r\n"
//				+ "                                \"over_ref\" : {\r\n"
//				+ "                                    \"sph\" : null,\r\n"
//				+ "                                    \"cyl\" : null,\r\n"
//				+ "                                    \"axs\" : null\r\n"
//				+ "                                },\r\n"
//				+ "                                \"va_without_cls\" : null\r\n"
//				+ "                            }\r\n"
//				+ "                        },\r\n"
//				+ "                        \"order_lens\" : {\r\n"
//				+ "                            \"od\" : {\r\n"
//				+ "                                \"brand\" : \"fargo\",\r\n"
//				+ "                                \"type\" : \"extended\",\r\n"
//				+ "                                \"diameter\" : \"96\",\r\n"
//				+ "                                \"code\" : \"8\"\r\n"
//				+ "                            },\r\n"
//				+ "                            \"os\" : {\r\n"
//				+ "                                \"brand\" : \"gov\",\r\n"
//				+ "                                \"type\" : \"premium\",\r\n"
//				+ "                                \"diameter\" : \"62\",\r\n"
//				+ "                                \"code\" : \"52\"\r\n"
//				+ "                            }\r\n"
//				+ "                        }\r\n"
//				+ "                    }\r\n"
//				+ "                }\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"prescription\" : {\r\n"
//				+ "            \"5\" : {\r\n"
//				+ "                \"medicine_id\" : \"8\",\r\n"
//				+ "                \"name\" : \"Laroscorbine 1g\",\r\n"
//				+ "                \"dose\" : \"1\",\r\n"
//				+ "                \"dose_unit\" : \"gi?t\",\r\n"
//				+ "                \"frequency\" : \"4\",\r\n"
//				+ "                \"duration\" : \"5\",\r\n"
//				+ "                \"usage\" : \"u?ng tru?c an\",\r\n"
//				+ "                \"total\" : 20,\r\n"
//				+ "                \"total_unit\" : \"gi?t\",\r\n"
//				+ "                \"quantity_num\" : \"1\",\r\n"
//				+ "                \"quantity_unit\" : \"l?\",\r\n"
//				+ "                \"description\" : \"u?ng tru?c an - 1 gi?t, 4 l?n/ngày, 5 ngày\"\r\n"
//				+ "            },\r\n"
//				+ "            \"6\" : {\r\n"
//				+ "                \"medicine_id\" : \"687\",\r\n"
//				+ "                \"name\" : \"Laroscorbine 1g (Acide ascorbique 1g/5ml)\",\r\n"
//				+ "                \"dose\" : \"1\",\r\n"
//				+ "                \"dose_unit\" : \"gi?t\",\r\n"
//				+ "                \"frequency\" : \"4\",\r\n"
//				+ "                \"duration\" : \"5\",\r\n"
//				+ "                \"usage\" : \"u?ng tru?c an\",\r\n"
//				+ "                \"total\" : 20,\r\n"
//				+ "                \"total_unit\" : \"gi?t\",\r\n"
//				+ "                \"quantity_num\" : \"1\",\r\n"
//				+ "                \"quantity_unit\" : \"l?\",\r\n"
//				+ "                \"description\" : \"u?ng tru?c an - 1 gi?t, 4 l?n/ngày, 5 ngày\"\r\n"
//				+ "            },\r\n"
//				+ "            \"7\" : {\r\n"
//				+ "                \"medicine_id\" : \"7\",\r\n"
//				+ "                \"name\" : \"Laroscorbine 500mg\",\r\n"
//				+ "                \"dose\" : \"1\",\r\n"
//				+ "                \"dose_unit\" : \"gi?t\",\r\n"
//				+ "                \"frequency\" : \"4\",\r\n"
//				+ "                \"duration\" : \"5\",\r\n"
//				+ "                \"usage\" : \"u?ng tru?c an\",\r\n"
//				+ "                \"total\" : 20,\r\n"
//				+ "                \"total_unit\" : \"gi?t\",\r\n"
//				+ "                \"quantity_num\" : \"1\",\r\n"
//				+ "                \"quantity_unit\" : \"l?\",\r\n"
//				+ "                \"description\" : \"u?ng tru?c an - 1 gi?t, 4 l?n/ngày, 5 ngày\"\r\n"
//				+ "            },\r\n"
//				+ "            \"instruction\" : \"u?ng ?a luôn\"\r\n"
//				+ "        }\r\n"
//				+ "    },\r\n"
//				+ "    \"summary\" : {\r\n"
//				+ "        \"cover_test\" : {\r\n"
//				+ "            \"type\" : \"tropia\",\r\n"
//				+ "            \"summary\" : {\r\n"
//				+ "                \"without_spec\" : {\r\n"
//				+ "                    \"distant\" : \"5? XP at distant\"\r\n"
//				+ "                },\r\n"
//				+ "                \"with_old_spec\" : {\r\n"
//				+ "                    \"os\" : {\r\n"
//				+ "                        \"near\" : \"13123? ET at near\"\r\n"
//				+ "                    }\r\n"
//				+ "                }\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"npc\" : \"{\\\"recover\\\":\\\"7\\\",\\\"break\\\":\\\"5\\\",\\\"nose\\\":\\\"no\\\"}\",\r\n"
//				+ "        \"visual_acuity\" : {\r\n"
//				+ "            \"distant_vision\" : {\r\n"
//				+ "                \"dataType\" : \"tp\",\r\n"
//				+ "                \"sc\" : {\r\n"
//				+ "                    \"od\" : \"7/10\",\r\n"
//				+ "                    \"os\" : \"9/10\",\r\n"
//				+ "                    \"ou\" : null\r\n"
//				+ "                },\r\n"
//				+ "                \"cc\" : {\r\n"
//				+ "                    \"od\" : null,\r\n"
//				+ "                    \"os\" : null,\r\n"
//				+ "                    \"ou\" : null\r\n"
//				+ "                }\r\n"
//				+ "            },\r\n"
//				+ "            \"near_vision\" : {\r\n"
//				+ "                \"od\" : null,\r\n"
//				+ "                \"os\" : null\r\n"
//				+ "            },\r\n"
//				+ "            \"other_type\" : {\r\n"
//				+ "                \"dataType\" : \"snellen\",\r\n"
//				+ "                \"sc\" : {\r\n"
//				+ "                    \"od\" : \"\",\r\n"
//				+ "                    \"os\" : \"\",\r\n"
//				+ "                    \"ou\" : \"20/10\"\r\n"
//				+ "                },\r\n"
//				+ "                \"cc\" : {\r\n"
//				+ "                    \"od\" : \"20/10\",\r\n"
//				+ "                    \"os\" : \"20/10\",\r\n"
//				+ "                    \"ou\" : \"20/10\"\r\n"
//				+ "                }\r\n"
//				+ "            }\r\n"
//				+ "        },\r\n"
//				+ "        \"distant_glass\" : {\r\n"
//				+ "            \"od\" : \"-0.75D - VA: 10/10\",\r\n"
//				+ "            \"os\" : \"plano / -0.75 x 5 - VA: 10/10\",\r\n"
//				+ "            \"nva_od\" : \"\",\r\n"
//				+ "            \"nva_os\" : \"\",\r\n"
//				+ "            \"add_od\" : \"\",\r\n"
//				+ "            \"add_os\" : \"\",\r\n"
//				+ "            \"pd\" : \"65 mm\"\r\n"
//				+ "        },\r\n"
//				+ "        \"IOP\" : \"{\\\"IOP\\\":{\\\"od\\\":\\\"11\\\",\\\"os\\\":\\\"12\\\"}}\",\r\n"
//				+ "        \"dry_objective\" : {\r\n"
//				+ "            \"od\" : \"-0.50D\",\r\n"
//				+ "            \"os\" : \"+0.50 / -1.00 x 180\",\r\n"
//				+ "            \"pd\" : \"63 mm\"\r\n"
//				+ "        },\r\n"
//				+ "        \"pd\" : \"63 mm\",\r\n"
//				+ "        \"wet_objective\" : {\r\n"
//				+ "            \"od\" : \"-0.50D\",\r\n"
//				+ "            \"os\" : \"+1.00 / -0.50 x 180\",\r\n"
//				+ "            \"pd\" : \"63 mm\",\r\n"
//				+ "            \"dilation\" : \"Cyclogyl 1%\"\r\n"
//				+ "        },\r\n"
//				+ "        \"subjective\" : {\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"des\" : \"-0.75D\",\r\n"
//				+ "                \"nva\" : \"G6@20-25 cm\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"add_nva\" : \"G6@20-25 cm\"\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"des\" : \"plano / -0.75 x 180\",\r\n"
//				+ "                \"nva\" : \"G5@35-40 cm\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"add_nva\" : \"G5@35-40 cm\"\r\n"
//				+ "            },\r\n"
//				+ "            \"bcva\" : \"10/10\",\r\n"
//				+ "            \"rule_od\" : \"c?n th?\",\r\n"
//				+ "            \"rule_os\" : \"lo?n th?\"\r\n"
//				+ "        },\r\n"
//				+ "        \"glass_prescription\" : {\r\n"
//				+ "            \"od\" : {\r\n"
//				+ "                \"des\" : \"-0.75D\",\r\n"
//				+ "                \"nva\" : \"G6@20-25 cm\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"add_nva\" : \"G6@20-25 cm\"\r\n"
//				+ "            },\r\n"
//				+ "            \"os\" : {\r\n"
//				+ "                \"des\" : \"plano / -0.75 x 180\",\r\n"
//				+ "                \"nva\" : \"G5@35-40 cm\",\r\n"
//				+ "                \"va\" : \"10/10\",\r\n"
//				+ "                \"add\" : \"\",\r\n"
//				+ "                \"add_nva\" : \"G5@35-40 cm\"\r\n"
//				+ "            },\r\n"
//				+ "            \"bcva\" : \"\",\r\n"
//				+ "            \"rule_od\" : \"c?n th?\",\r\n"
//				+ "            \"rule_os\" : \"lo?n th?\",\r\n"
//				+ "            \"glass_type\" : \"progressive glass\",\r\n"
//				+ "            \"glass_description\" : \"\",\r\n"
//				+ "            \"progressive_type\" : \"PALs\",\r\n"
//				+ "            \"indication\" : \"no glass\"\r\n"
//				+ "        },\r\n"
//				+ "        \"aa\" : \"{\\\"method\\\":\\\"pu\\\",\\\"OD\\\":\\\"12\\\",\\\"OS\\\":\\\"10\\\"}\",\r\n"
//				+ "        \"visual_field\" : \"{\\\"OD\\\":\\\"restricted at  Superiotemporal\\\",\\\"OS\\\":\\\"restricted at  Inferiotemporal, Inferionasal\\\"}\",\r\n"
//				+ "        \"pupillary\" : \"{\\\"od\\\":{\\\"p\\\":\\\"\\\",\\\"mg\\\":{\\\"status\\\":\\\"negative\\\",\\\"degree\\\":\\\"0\\\"}},\\\"os\\\":{\\\"p\\\":\\\"\\\",\\\"mg\\\":{\\\"status\\\":\\\"negative\\\",\\\"degree\\\":\\\"0\\\"}}}\",\r\n"
//				+ "        \"near_glass\" : {\r\n"
//				+ "            \"od\" : \"+1.75DD\",\r\n"
//				+ "            \"os\" : \"+2.50 / -0.75 x 5\",\r\n"
//				+ "            \"nva_od\" : \"G5@35-40cm\",\r\n"
//				+ "            \"nva_os\" : \"G5@35-40cm\",\r\n"
//				+ "            \"add_od\" : \"\",\r\n"
//				+ "            \"add_os\" : \"\",\r\n"
//				+ "            \"pd\" : \"63 mm\"\r\n"
//				+ "        }\r\n"
//				+ "    }\r\n"
//				+ "}";
		
//		String input = "{\r\n"
//				+ "    \"abbreviation\": \"GMT\",\r\n"
//				+ "    \"client_ip\": \"115.79.140.65\",\r\n"
//				+ "    \"datetime\": \"2020-11-23T15:51:31.248095+00:00\",\r\n"
//				+ "    \"day_of_week\": 1,\r\n"
//				+ "    \"day_of_year\": 328,\r\n"
//				+ "    \"dst\": false,\r\n"
//				+ "    \"dst_from\": null,\r\n"
//				+ "    \"dst_offset\": 0,\r\n"
//				+ "    \"dst_until\": null,\r\n"
//				+ "    \"raw_offset\": 0,\r\n"
//				+ "    \"timezone\": \"Africa/Abidjan\",\r\n"
//				+ "    \"unixtime\": 1606146691,\r\n"
//				+ "    \"utc_datetime\": \"2020-11-23T15:51:31.248095+00:00\",\r\n"
//				+ "    \"utc_offset\": \"+00:00\",\r\n"
//				+ "    \"week_number\": 48\r\n"
//				+ "}";
		
		// Test nested lists
//		String input = "{\r\n"
//				+ "  \"RawDocsCount\": 3555648,\r\n"
//				+ "  \"RawDocsSearchTime\": 14056,\r\n"
//				+ "  \"ReRankSearchTime\": 1182,\r\n"
//				+ "  \"CacheHit\": false,\r\n"
//				+ "  \"trial\": 1,\r\n"
//				+ "  \"limit\": 9,\r\n"
//				+ "  \"limit_ttl\": 60,\r\n"
//				+ "  \"quota\": 150,\r\n"
//				+ "  \"quota_ttl\": 86400,\r\n"
//				+ "  \"strings\": [\"str\"],\r\n"
//				+ "  \"lists\": [[\"\"]]\r\n"
//				+ "}";
		
		// Test nested objects
		String input = "{\r\n"
				+ "  \"time\": 23423.123,\r\n"
				+ "  \"CacheHit\": false,\r\n"
				+ "  \"trial\": 1,\r\n"
				+ "  \"strings\": [\"str\"],\r\n"
				+ "  \"location\": {\r\n"
				+ "    \"address\": {\r\n"
				+ "  	  \"ip\": \"192.175.3.1\",\r\n"
				+ "  	  \"latitude\": 12443.35,\r\n"
				+ "  	  \"longitude\": 123.423\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "}";
		
		// Test list of objects
//		String input = "{\r\n"
//				+ "  \"RawDocsCount\": 3555648,\r\n"
//				+ "  \"RawDocsSearchTime\": 14056,\r\n"
//				+ "  \"ReRankSearchTime\": 1182,\r\n"
//				+ "  \"CacheHit\": false,\r\n"
//				+ "  \"trial\": 1,\r\n"
//				+ "  \"limit\": 9,\r\n"
//				+ "  \"limit_ttl\": 60,\r\n"
//				+ "  \"quota\": 150,\r\n"
//				+ "  \"quota_ttl\": 86400,\r\n"
//				+ "  \"strings\": [\"str\"],\r\n"
//				+ "  \"docs\": [\r\n"
//				+ "    {\r\n"
//				+ "      \"from\": 663.17,\r\n"
//				+ "      \"to\": 665.42,\r\n"
//				+ "      \"anilist_id\": 98444,\r\n"
//				+ "      \"at\": 665.08,\r\n"
//				+ "      \"season\": \"2018-01\",\r\n"
//				+ "      \"anime\": \"搖曳露營\",\r\n"
//				+ "      \"filename\": \"[Ohys-Raws] Yuru Camp - 05 (AT-X 1280x720 x264 AAC).mp4\",\r\n"
//				+ "      \"episode\": 5,\r\n"
//				+ "      \"tokenthumb\": \"bB-8KQuoc6u-1SfzuVnDMw\",\r\n"
//				+ "      \"similarity\": 0.9563952960290518,\r\n"
//				+ "      \"title\": \"ゆるキャン△\",\r\n"
//				+ "      \"title_native\": \"ゆるキャン△\",\r\n"
//				+ "      \"title_chinese\": \"搖曳露營\",\r\n"
//				+ "      \"title_english\": \"Laid-Back Camp\",\r\n"
//				+ "      \"title_romaji\": \"Yuru Camp△\",\r\n"
//				+ "      \"mal_id\": 34798,\r\n"
//				+ "      \"synonyms\": [\"Yurucamp\", \"Yurukyan△\"],\r\n"
//				+ "      \"synonyms_chinese\": [{\"empty\":null}],\r\n"
//				+ "      \"is_adult\": false\r\n"
//				+ "    }\r\n"
//				+ "  ]\r\n"
//				+ "}";

		// Test Lexer
//		JsonLexer lexer = new JsonLexer(input);
//		Token<Type> token;
//		do {
//			token = lexer.getNextToken();
//			System.out.println(token);
//		} while (token.type != Type.EOF);
		
		// Test Parser + Printer
//		JsonParser parser = new JsonParser(lexer);
//		AST tree = parser.parse();
//		System.out.println(tree);
//		JsonPrintInterpreter interpreter = new JsonPrintInterpreter(input);
//		interpreter.interpret();
		
		// Debug input
//		System.out.println(input);
		
		// Measure compilation/interpretation
		long duration = System.currentTimeMillis();
		try {
			JsonGenerator generator = new JsonGenerator("NestedObject", input);
			Files.writeString(Paths.get("out.java"), generator.interpret().toString());
//			System.out.println(sb);
		} finally {
			System.out.println(
					String.format(
							"Executed for : %d ms", 
							System.currentTimeMillis() - duration));
		}
	}
}