package tests;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import json.interpreter.JsonGenerator;

public class TestJsonGenerator {

	@Tag("slow")
    @Test
    public void generateJsonFromRequest() throws Exception {
		String[] names = {"TimeResult", "DocsResult", "LocationResult", "AnimeResult"},
				inputs = {INPUT1, INPUT2, INPUT3, INPUT4},
				expecteds = {EXPECTED1, EXPECTED2, EXPECTED3, EXPECTED4};
		for (int i=0; i<names.length; i++) {
		    JsonGenerator generator = new JsonGenerator(names[i], inputs[i]);
		    String result = cleanup(generator.interpret().toString()),
		    		expected = cleanup(expecteds[i]);
		    assertEquals(expected, result, "JSON transpiler output is different");
		}
    }
	
	public static String cleanup(String input) {
		return input.replace("\r\n", "\n").trim();
	}
	
	private static String INPUT1 = "{\r\n"
				+ "    \"abbreviation\": \"GMT\",\r\n"
				+ "    \"client_ip\": \"115.79.140.65\",\r\n"
				+ "    \"datetime\": \"2020-11-23T15:51:31.248095+00:00\",\r\n"
				+ "    \"day_of_week\": 1,\r\n"
				+ "    \"day_of_year\": 328,\r\n"
				+ "    \"dst\": false,\r\n"
				+ "    \"dst_from\": null,\r\n"
				+ "    \"dst_offset\": 0,\r\n"
				+ "    \"dst_until\": null,\r\n"
				+ "    \"raw_offset\": 0,\r\n"
				+ "    \"timezone\": \"Africa/Abidjan\",\r\n"
				+ "    \"unixtime\": 1606146691,\r\n"
				+ "    \"utc_datetime\": \"2020-11-23T15:51:31.248095+00:00\",\r\n"
				+ "    \"utc_offset\": \"+00:00\",\r\n"
				+ "    \"week_number\": 48\r\n"
				+ "}",
			EXPECTED1 = "import java.io.Serializable;\n"
				+ "\n"
				+ "\n"
				+ "public final class TimeResult implements Serializable {\r\n"
				+ "	private static final long serialVersionUID = 1L;\r\n"
				+ "	public int unixtime;\r\n"
				+ "	public String utc_offset;\r\n"
				+ "	public boolean dst;\r\n"
				+ "	public int day_of_year;\r\n"
				+ "	public String timezone;\r\n"
				+ "	public String abbreviation;\r\n"
				+ "	public int dst_offset;\r\n"
				+ "	public String utc_datetime;\r\n"
				+ "	public String datetime;\r\n"
				+ "	public Object dst_until;\r\n"
				+ "	public String client_ip;\r\n"
				+ "	public Object dst_from;\r\n"
				+ "	public int week_number;\r\n"
				+ "	public int day_of_week;\r\n"
				+ "	public int raw_offset;\r\n"
				+ "\r\n"
				+ "	public TimeResult(int unixtime, String utc_offset, boolean dst, int day_of_year, String timezone, String abbreviation, int dst_offset, String utc_datetime, String datetime, Object dst_until, String client_ip, Object dst_from, int week_number, int day_of_week, int raw_offset) {\r\n"
				+ "		this.unixtime = unixtime;\r\n"
				+ "		this.utc_offset = utc_offset;\r\n"
				+ "		this.dst = dst;\r\n"
				+ "		this.day_of_year = day_of_year;\r\n"
				+ "		this.timezone = timezone;\r\n"
				+ "		this.abbreviation = abbreviation;\r\n"
				+ "		this.dst_offset = dst_offset;\r\n"
				+ "		this.utc_datetime = utc_datetime;\r\n"
				+ "		this.datetime = datetime;\r\n"
				+ "		this.dst_until = dst_until;\r\n"
				+ "		this.client_ip = client_ip;\r\n"
				+ "		this.dst_from = dst_from;\r\n"
				+ "		this.week_number = week_number;\r\n"
				+ "		this.day_of_week = day_of_week;\r\n"
				+ "		this.raw_offset = raw_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getUnixtime() {\r\n"
				+ "		return unixtime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String getUtc_offset() {\r\n"
				+ "		return utc_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public boolean getDst() {\r\n"
				+ "		return dst;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getDay_of_year() {\r\n"
				+ "		return day_of_year;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String getTimezone() {\r\n"
				+ "		return timezone;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String getAbbreviation() {\r\n"
				+ "		return abbreviation;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getDst_offset() {\r\n"
				+ "		return dst_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String getUtc_datetime() {\r\n"
				+ "		return utc_datetime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String getDatetime() {\r\n"
				+ "		return datetime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public Object getDst_until() {\r\n"
				+ "		return dst_until;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String getClient_ip() {\r\n"
				+ "		return client_ip;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public Object getDst_from() {\r\n"
				+ "		return dst_from;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getWeek_number() {\r\n"
				+ "		return week_number;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getDay_of_week() {\r\n"
				+ "		return day_of_week;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getRaw_offset() {\r\n"
				+ "		return raw_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setUnixtime(int unixtime) {\r\n"
				+ "		this.unixtime = unixtime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setUtc_offset(String utc_offset) {\r\n"
				+ "		this.utc_offset = utc_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDst(boolean dst) {\r\n"
				+ "		this.dst = dst;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDay_of_year(int day_of_year) {\r\n"
				+ "		this.day_of_year = day_of_year;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setTimezone(String timezone) {\r\n"
				+ "		this.timezone = timezone;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setAbbreviation(String abbreviation) {\r\n"
				+ "		this.abbreviation = abbreviation;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDst_offset(int dst_offset) {\r\n"
				+ "		this.dst_offset = dst_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setUtc_datetime(String utc_datetime) {\r\n"
				+ "		this.utc_datetime = utc_datetime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDatetime(String datetime) {\r\n"
				+ "		this.datetime = datetime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDst_until(Object dst_until) {\r\n"
				+ "		this.dst_until = dst_until;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setClient_ip(String client_ip) {\r\n"
				+ "		this.client_ip = client_ip;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDst_from(Object dst_from) {\r\n"
				+ "		this.dst_from = dst_from;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setWeek_number(int week_number) {\r\n"
				+ "		this.week_number = week_number;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDay_of_week(int day_of_week) {\r\n"
				+ "		this.day_of_week = day_of_week;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setRaw_offset(int raw_offset) {\r\n"
				+ "		this.raw_offset = raw_offset;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	@Override\r\n"
				+ "	public String toString() {\r\n"
				+ "		return new StringBuilder()\r\n"
				+ "			.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "			.append(\"unixtime: \").append(unixtime+\",\\n\")\r\n"
				+ "			.append(\"utc_offset: \").append(utc_offset+\",\\n\")\r\n"
				+ "			.append(\"dst: \").append(dst+\",\\n\")\r\n"
				+ "			.append(\"day_of_year: \").append(day_of_year+\",\\n\")\r\n"
				+ "			.append(\"timezone: \").append(timezone+\",\\n\")\r\n"
				+ "			.append(\"abbreviation: \").append(abbreviation+\",\\n\")\r\n"
				+ "			.append(\"dst_offset: \").append(dst_offset+\",\\n\")\r\n"
				+ "			.append(\"utc_datetime: \").append(utc_datetime+\",\\n\")\r\n"
				+ "			.append(\"datetime: \").append(datetime+\",\\n\")\r\n"
				+ "			.append(\"dst_until: \").append(dst_until+\",\\n\")\r\n"
				+ "			.append(\"client_ip: \").append(client_ip+\",\\n\")\r\n"
				+ "			.append(\"dst_from: \").append(dst_from+\",\\n\")\r\n"
				+ "			.append(\"week_number: \").append(week_number+\",\\n\")\r\n"
				+ "			.append(\"day_of_week: \").append(day_of_week+\",\\n\")\r\n"
				+ "			.append(\"raw_offset: \").append(raw_offset+\",\\n\")\r\n"
				+ "			.append(\"\\n}\").toString();\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public static class Builder {\r\n"
				+ "		public int unixtime;\r\n"
				+ "		public String utc_offset;\r\n"
				+ "		public boolean dst;\r\n"
				+ "		public int day_of_year;\r\n"
				+ "		public String timezone;\r\n"
				+ "		public String abbreviation;\r\n"
				+ "		public int dst_offset;\r\n"
				+ "		public String utc_datetime;\r\n"
				+ "		public String datetime;\r\n"
				+ "		public Object dst_until;\r\n"
				+ "		public String client_ip;\r\n"
				+ "		public Object dst_from;\r\n"
				+ "		public int week_number;\r\n"
				+ "		public int day_of_week;\r\n"
				+ "		public int raw_offset;\r\n"
				+ "\r\n"
				+ "		public Builder setUnixtime(int unixtime) {\r\n"
				+ "			this.unixtime = unixtime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setUtc_offset(String utc_offset) {\r\n"
				+ "			this.utc_offset = utc_offset;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDst(boolean dst) {\r\n"
				+ "			this.dst = dst;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDay_of_year(int day_of_year) {\r\n"
				+ "			this.day_of_year = day_of_year;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setTimezone(String timezone) {\r\n"
				+ "			this.timezone = timezone;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setAbbreviation(String abbreviation) {\r\n"
				+ "			this.abbreviation = abbreviation;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDst_offset(int dst_offset) {\r\n"
				+ "			this.dst_offset = dst_offset;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setUtc_datetime(String utc_datetime) {\r\n"
				+ "			this.utc_datetime = utc_datetime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDatetime(String datetime) {\r\n"
				+ "			this.datetime = datetime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDst_until(Object dst_until) {\r\n"
				+ "			this.dst_until = dst_until;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setClient_ip(String client_ip) {\r\n"
				+ "			this.client_ip = client_ip;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDst_from(Object dst_from) {\r\n"
				+ "			this.dst_from = dst_from;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setWeek_number(int week_number) {\r\n"
				+ "			this.week_number = week_number;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDay_of_week(int day_of_week) {\r\n"
				+ "			this.day_of_week = day_of_week;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setRaw_offset(int raw_offset) {\r\n"
				+ "			this.raw_offset = raw_offset;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public TimeResult build() {\r\n"
				+ "			return new TimeResult(unixtime,utc_offset,dst,day_of_year,timezone,abbreviation,dst_offset,utc_datetime,datetime,dst_until,client_ip,dst_from,week_number,day_of_week,raw_offset);\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "}";
	// Test nested lists
	public static String INPUT2 = "{\r\n"
				+ "  \"RawDocsCount\": 3555648,\r\n"
				+ "  \"RawDocsSearchTime\": 14056,\r\n"
				+ "  \"ReRankSearchTime\": 1182,\r\n"
				+ "  \"CacheHit\": false,\r\n"
				+ "  \"trial\": 1,\r\n"
				+ "  \"limit\": 9,\r\n"
				+ "  \"limit_ttl\": 60,\r\n"
				+ "  \"quota\": 150,\r\n"
				+ "  \"quota_ttl\": 86400,\r\n"
				+ "  \"strings\": [\"str\"],\r\n"
				+ "  \"lists\": [[\"\"]]\r\n"
				+ "}",
			EXPECTED2 = "import java.io.Serializable;\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "public final class DocsResult implements Serializable {\r\n"
				+ "	private static final long serialVersionUID = 1L;\r\n"
				+ "	public int RawDocsCount;\r\n"
				+ "	public boolean CacheHit;\r\n"
				+ "	public String[] strings;\r\n"
				+ "	public int limit_ttl;\r\n"
				+ "	public int RawDocsSearchTime;\r\n"
				+ "	public String[][] lists;\r\n"
				+ "	public int quota;\r\n"
				+ "	public int limit;\r\n"
				+ "	public int ReRankSearchTime;\r\n"
				+ "	public int quota_ttl;\r\n"
				+ "	public int trial;\r\n"
				+ "\r\n"
				+ "	public DocsResult(int RawDocsCount, boolean CacheHit, String[] strings, int limit_ttl, int RawDocsSearchTime, String[][] lists, int quota, int limit, int ReRankSearchTime, int quota_ttl, int trial) {\r\n"
				+ "		this.RawDocsCount = RawDocsCount;\r\n"
				+ "		this.CacheHit = CacheHit;\r\n"
				+ "		this.strings = strings;\r\n"
				+ "		this.limit_ttl = limit_ttl;\r\n"
				+ "		this.RawDocsSearchTime = RawDocsSearchTime;\r\n"
				+ "		this.lists = lists;\r\n"
				+ "		this.quota = quota;\r\n"
				+ "		this.limit = limit;\r\n"
				+ "		this.ReRankSearchTime = ReRankSearchTime;\r\n"
				+ "		this.quota_ttl = quota_ttl;\r\n"
				+ "		this.trial = trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getRawDocsCount() {\r\n"
				+ "		return RawDocsCount;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public boolean getCacheHit() {\r\n"
				+ "		return CacheHit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String[] getStrings() {\r\n"
				+ "		return strings;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getLimit_ttl() {\r\n"
				+ "		return limit_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getRawDocsSearchTime() {\r\n"
				+ "		return RawDocsSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String[][] getLists() {\r\n"
				+ "		return lists;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getQuota() {\r\n"
				+ "		return quota;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getLimit() {\r\n"
				+ "		return limit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getReRankSearchTime() {\r\n"
				+ "		return ReRankSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getQuota_ttl() {\r\n"
				+ "		return quota_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getTrial() {\r\n"
				+ "		return trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setRawDocsCount(int RawDocsCount) {\r\n"
				+ "		this.RawDocsCount = RawDocsCount;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setCacheHit(boolean CacheHit) {\r\n"
				+ "		this.CacheHit = CacheHit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setStrings(String[] strings) {\r\n"
				+ "		this.strings = strings;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setLimit_ttl(int limit_ttl) {\r\n"
				+ "		this.limit_ttl = limit_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setRawDocsSearchTime(int RawDocsSearchTime) {\r\n"
				+ "		this.RawDocsSearchTime = RawDocsSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setLists(String[][] lists) {\r\n"
				+ "		this.lists = lists;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setQuota(int quota) {\r\n"
				+ "		this.quota = quota;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setLimit(int limit) {\r\n"
				+ "		this.limit = limit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setReRankSearchTime(int ReRankSearchTime) {\r\n"
				+ "		this.ReRankSearchTime = ReRankSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setQuota_ttl(int quota_ttl) {\r\n"
				+ "		this.quota_ttl = quota_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setTrial(int trial) {\r\n"
				+ "		this.trial = trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	@Override\r\n"
				+ "	public String toString() {\r\n"
				+ "		return new StringBuilder()\r\n"
				+ "			.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "			.append(\"RawDocsCount: \").append(RawDocsCount+\",\\n\")\r\n"
				+ "			.append(\"CacheHit: \").append(CacheHit+\",\\n\")\r\n"
				+ "			.append(\"strings: \").append(strings+\",\\n\")\r\n"
				+ "			.append(\"limit_ttl: \").append(limit_ttl+\",\\n\")\r\n"
				+ "			.append(\"RawDocsSearchTime: \").append(RawDocsSearchTime+\",\\n\")\r\n"
				+ "			.append(\"lists: \").append(lists+\",\\n\")\r\n"
				+ "			.append(\"quota: \").append(quota+\",\\n\")\r\n"
				+ "			.append(\"limit: \").append(limit+\",\\n\")\r\n"
				+ "			.append(\"ReRankSearchTime: \").append(ReRankSearchTime+\",\\n\")\r\n"
				+ "			.append(\"quota_ttl: \").append(quota_ttl+\",\\n\")\r\n"
				+ "			.append(\"trial: \").append(trial+\",\\n\")\r\n"
				+ "			.append(\"\\n}\").toString();\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public static class Builder {\r\n"
				+ "		public int RawDocsCount;\r\n"
				+ "		public boolean CacheHit;\r\n"
				+ "		public String[] strings;\r\n"
				+ "		public int limit_ttl;\r\n"
				+ "		public int RawDocsSearchTime;\r\n"
				+ "		public String[][] lists;\r\n"
				+ "		public int quota;\r\n"
				+ "		public int limit;\r\n"
				+ "		public int ReRankSearchTime;\r\n"
				+ "		public int quota_ttl;\r\n"
				+ "		public int trial;\r\n"
				+ "\r\n"
				+ "		public Builder setRawDocsCount(int RawDocsCount) {\r\n"
				+ "			this.RawDocsCount = RawDocsCount;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setCacheHit(boolean CacheHit) {\r\n"
				+ "			this.CacheHit = CacheHit;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setStrings(String[] strings) {\r\n"
				+ "			this.strings = strings;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setLimit_ttl(int limit_ttl) {\r\n"
				+ "			this.limit_ttl = limit_ttl;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setRawDocsSearchTime(int RawDocsSearchTime) {\r\n"
				+ "			this.RawDocsSearchTime = RawDocsSearchTime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setLists(String[][] lists) {\r\n"
				+ "			this.lists = lists;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setQuota(int quota) {\r\n"
				+ "			this.quota = quota;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setLimit(int limit) {\r\n"
				+ "			this.limit = limit;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setReRankSearchTime(int ReRankSearchTime) {\r\n"
				+ "			this.ReRankSearchTime = ReRankSearchTime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setQuota_ttl(int quota_ttl) {\r\n"
				+ "			this.quota_ttl = quota_ttl;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setTrial(int trial) {\r\n"
				+ "			this.trial = trial;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public DocsResult build() {\r\n"
				+ "			return new DocsResult(RawDocsCount,CacheHit,strings,limit_ttl,RawDocsSearchTime,lists,quota,limit,ReRankSearchTime,quota_ttl,trial);\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "}";
	
	// Test nested objects
	public static String INPUT3 = "{\r\n"
				+ "  \"time\": 23423.123,\r\n"
				+ "  \"CacheHit\": false,\r\n"
				+ "  \"trial\": 1,\r\n"
				+ "  \"strings\": [\"str\"],\r\n"
				+ "  \"location\": {\r\n"
				+ "    \"address\": {\r\n"
				+ "  	  \"ip\": \"192.175.3.1\",\r\n"
				+ "  	  \"latitude\": 12443.35,\r\n"
				+ "  	  \"longitude\": 123.423\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "}",
			EXPECTED3 = "import java.io.Serializable;\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "public final class LocationResult implements Serializable {\r\n"
				+ "	private static final long serialVersionUID = 1L;\r\n"
				+ "	public boolean CacheHit;\r\n"
				+ "	public String[] strings;\r\n"
				+ "	public Location location;\r\n"
				+ "	public double time;\r\n"
				+ "	public int trial;\r\n"
				+ "\r\n"
				+ "	public LocationResult(boolean CacheHit, String[] strings, Location location, double time, int trial) {\r\n"
				+ "		this.CacheHit = CacheHit;\r\n"
				+ "		this.strings = strings;\r\n"
				+ "		this.location = location;\r\n"
				+ "		this.time = time;\r\n"
				+ "		this.trial = trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public boolean getCacheHit() {\r\n"
				+ "		return CacheHit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String[] getStrings() {\r\n"
				+ "		return strings;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public Location getLocation() {\r\n"
				+ "		return location;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public double getTime() {\r\n"
				+ "		return time;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getTrial() {\r\n"
				+ "		return trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setCacheHit(boolean CacheHit) {\r\n"
				+ "		this.CacheHit = CacheHit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setStrings(String[] strings) {\r\n"
				+ "		this.strings = strings;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setLocation(Location location) {\r\n"
				+ "		this.location = location;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setTime(double time) {\r\n"
				+ "		this.time = time;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setTrial(int trial) {\r\n"
				+ "		this.trial = trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	@Override\r\n"
				+ "	public String toString() {\r\n"
				+ "		return new StringBuilder()\r\n"
				+ "			.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "			.append(\"CacheHit: \").append(CacheHit+\",\\n\")\r\n"
				+ "			.append(\"strings: \").append(strings+\",\\n\")\r\n"
				+ "			.append(\"location: \").append(location+\",\\n\")\r\n"
				+ "			.append(\"time: \").append(time+\",\\n\")\r\n"
				+ "			.append(\"trial: \").append(trial+\",\\n\")\r\n"
				+ "			.append(\"\\n}\").toString();\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public static class Builder {\r\n"
				+ "		public boolean CacheHit;\r\n"
				+ "		public String[] strings;\r\n"
				+ "		public Location location;\r\n"
				+ "		public double time;\r\n"
				+ "		public int trial;\r\n"
				+ "\r\n"
				+ "		public Builder setCacheHit(boolean CacheHit) {\r\n"
				+ "			this.CacheHit = CacheHit;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setStrings(String[] strings) {\r\n"
				+ "			this.strings = strings;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setLocation(Location location) {\r\n"
				+ "			this.location = location;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setTime(double time) {\r\n"
				+ "			this.time = time;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setTrial(int trial) {\r\n"
				+ "			this.trial = trial;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public LocationResult build() {\r\n"
				+ "			return new LocationResult(CacheHit,strings,location,time,trial);\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public static final class Location implements Serializable {\r\n"
				+ "		private static final long serialVersionUID = 1L;\r\n"
				+ "		public Address address;\r\n"
				+ "\r\n"
				+ "		public Location(Address address) {\r\n"
				+ "			this.address = address;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Address getAddress() {\r\n"
				+ "			return address;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setAddress(Address address) {\r\n"
				+ "			this.address = address;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		@Override\r\n"
				+ "		public String toString() {\r\n"
				+ "			return new StringBuilder()\r\n"
				+ "				.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "				.append(\"address: \").append(address+\",\\n\")\r\n"
				+ "				.append(\"\\n}\").toString();\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public static class Builder {\r\n"
				+ "			public Address address;\r\n"
				+ "\r\n"
				+ "			public Builder setAddress(Address address) {\r\n"
				+ "				this.address = address;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Location build() {\r\n"
				+ "				return new Location(address);\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public static final class Address implements Serializable {\r\n"
				+ "			private static final long serialVersionUID = 1L;\r\n"
				+ "			public String ip;\r\n"
				+ "			public double latitude;\r\n"
				+ "			public double longitude;\r\n"
				+ "\r\n"
				+ "			public Address(String ip, double latitude, double longitude) {\r\n"
				+ "				this.ip = ip;\r\n"
				+ "				this.latitude = latitude;\r\n"
				+ "				this.longitude = longitude;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public String getIp() {\r\n"
				+ "				return ip;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public double getLatitude() {\r\n"
				+ "				return latitude;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public double getLongitude() {\r\n"
				+ "				return longitude;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public void setIp(String ip) {\r\n"
				+ "				this.ip = ip;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public void setLatitude(double latitude) {\r\n"
				+ "				this.latitude = latitude;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public void setLongitude(double longitude) {\r\n"
				+ "				this.longitude = longitude;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			@Override\r\n"
				+ "			public String toString() {\r\n"
				+ "				return new StringBuilder()\r\n"
				+ "					.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "					.append(\"ip: \").append(ip+\",\\n\")\r\n"
				+ "					.append(\"latitude: \").append(latitude+\",\\n\")\r\n"
				+ "					.append(\"longitude: \").append(longitude+\",\\n\")\r\n"
				+ "					.append(\"\\n}\").toString();\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public static class Builder {\r\n"
				+ "				public String ip;\r\n"
				+ "				public double latitude;\r\n"
				+ "				public double longitude;\r\n"
				+ "\r\n"
				+ "				public Builder setIp(String ip) {\r\n"
				+ "					this.ip = ip;\r\n"
				+ "					return this;\r\n"
				+ "				}\r\n"
				+ "\r\n"
				+ "				public Builder setLatitude(double latitude) {\r\n"
				+ "					this.latitude = latitude;\r\n"
				+ "					return this;\r\n"
				+ "				}\r\n"
				+ "\r\n"
				+ "				public Builder setLongitude(double longitude) {\r\n"
				+ "					this.longitude = longitude;\r\n"
				+ "					return this;\r\n"
				+ "				}\r\n"
				+ "\r\n"
				+ "				public Address build() {\r\n"
				+ "					return new Address(ip,latitude,longitude);\r\n"
				+ "				}\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "}";
	
	// Test nested list of objects
	public static String INPUT4 = "{\r\n"
				+ "  \"RawDocsCount\": 3555648,\r\n"
				+ "  \"RawDocsSearchTime\": 14056,\r\n"
				+ "  \"ReRankSearchTime\": 1182,\r\n"
				+ "  \"CacheHit\": false,\r\n"
				+ "  \"trial\": 1,\r\n"
				+ "  \"limit\": 9,\r\n"
				+ "  \"limit_ttl\": 60,\r\n"
				+ "  \"quota\": 150,\r\n"
				+ "  \"quota_ttl\": 86400,\r\n"
				+ "  \"strings\": [\"str\"],\r\n"
				+ "  \"docs\": [\r\n"
				+ "    {\r\n"
				+ "      \"from\": 663.17,\r\n"
				+ "      \"to\": 665.42,\r\n"
				+ "      \"anilist_id\": 98444,\r\n"
				+ "      \"at\": 665.08,\r\n"
				+ "      \"season\": \"2018-01\",\r\n"
				+ "      \"anime\": \"搖曳露營\",\r\n"
				+ "      \"filename\": \"[Ohys-Raws] Yuru Camp - 05 (AT-X 1280x720 x264 AAC).mp4\",\r\n"
				+ "      \"episode\": 5,\r\n"
				+ "      \"tokenthumb\": \"bB-8KQuoc6u-1SfzuVnDMw\",\r\n"
				+ "      \"similarity\": 0.9563952960290518,\r\n"
				+ "      \"title\": \"ゆるキャン△\",\r\n"
				+ "      \"title_native\": \"ゆるキャン△\",\r\n"
				+ "      \"title_chinese\": \"搖曳露營\",\r\n"
				+ "      \"title_english\": \"Laid-Back Camp\",\r\n"
				+ "      \"title_romaji\": \"Yuru Camp△\",\r\n"
				+ "      \"mal_id\": 34798,\r\n"
				+ "      \"synonyms\": [\"Yurucamp\", \"Yurukyan△\"],\r\n"
				+ "      \"synonyms_chinese\": [{\"empty\":null}],\r\n"
				+ "      \"is_adult\": false\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}",
			EXPECTED4 = "import java.io.Serializable;\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "public final class AnimeResult implements Serializable {\r\n"
				+ "	private static final long serialVersionUID = 1L;\r\n"
				+ "	public int RawDocsCount;\r\n"
				+ "	public boolean CacheHit;\r\n"
				+ "	public String[] strings;\r\n"
				+ "	public Doc[] docs;\r\n"
				+ "	public int limit_ttl;\r\n"
				+ "	public int RawDocsSearchTime;\r\n"
				+ "	public int quota;\r\n"
				+ "	public int limit;\r\n"
				+ "	public int ReRankSearchTime;\r\n"
				+ "	public int quota_ttl;\r\n"
				+ "	public int trial;\r\n"
				+ "\r\n"
				+ "	public AnimeResult(int RawDocsCount, boolean CacheHit, String[] strings, Doc[] docs, int limit_ttl, int RawDocsSearchTime, int quota, int limit, int ReRankSearchTime, int quota_ttl, int trial) {\r\n"
				+ "		this.RawDocsCount = RawDocsCount;\r\n"
				+ "		this.CacheHit = CacheHit;\r\n"
				+ "		this.strings = strings;\r\n"
				+ "		this.docs = docs;\r\n"
				+ "		this.limit_ttl = limit_ttl;\r\n"
				+ "		this.RawDocsSearchTime = RawDocsSearchTime;\r\n"
				+ "		this.quota = quota;\r\n"
				+ "		this.limit = limit;\r\n"
				+ "		this.ReRankSearchTime = ReRankSearchTime;\r\n"
				+ "		this.quota_ttl = quota_ttl;\r\n"
				+ "		this.trial = trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getRawDocsCount() {\r\n"
				+ "		return RawDocsCount;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public boolean getCacheHit() {\r\n"
				+ "		return CacheHit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public String[] getStrings() {\r\n"
				+ "		return strings;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public Doc[] getDocs() {\r\n"
				+ "		return docs;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getLimit_ttl() {\r\n"
				+ "		return limit_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getRawDocsSearchTime() {\r\n"
				+ "		return RawDocsSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getQuota() {\r\n"
				+ "		return quota;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getLimit() {\r\n"
				+ "		return limit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getReRankSearchTime() {\r\n"
				+ "		return ReRankSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getQuota_ttl() {\r\n"
				+ "		return quota_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public int getTrial() {\r\n"
				+ "		return trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setRawDocsCount(int RawDocsCount) {\r\n"
				+ "		this.RawDocsCount = RawDocsCount;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setCacheHit(boolean CacheHit) {\r\n"
				+ "		this.CacheHit = CacheHit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setStrings(String[] strings) {\r\n"
				+ "		this.strings = strings;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setDocs(Doc[] docs) {\r\n"
				+ "		this.docs = docs;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setLimit_ttl(int limit_ttl) {\r\n"
				+ "		this.limit_ttl = limit_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setRawDocsSearchTime(int RawDocsSearchTime) {\r\n"
				+ "		this.RawDocsSearchTime = RawDocsSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setQuota(int quota) {\r\n"
				+ "		this.quota = quota;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setLimit(int limit) {\r\n"
				+ "		this.limit = limit;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setReRankSearchTime(int ReRankSearchTime) {\r\n"
				+ "		this.ReRankSearchTime = ReRankSearchTime;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setQuota_ttl(int quota_ttl) {\r\n"
				+ "		this.quota_ttl = quota_ttl;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public void setTrial(int trial) {\r\n"
				+ "		this.trial = trial;\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	@Override\r\n"
				+ "	public String toString() {\r\n"
				+ "		return new StringBuilder()\r\n"
				+ "			.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "			.append(\"RawDocsCount: \").append(RawDocsCount+\",\\n\")\r\n"
				+ "			.append(\"CacheHit: \").append(CacheHit+\",\\n\")\r\n"
				+ "			.append(\"strings: \").append(strings+\",\\n\")\r\n"
				+ "			.append(\"docs: \").append(docs+\",\\n\")\r\n"
				+ "			.append(\"limit_ttl: \").append(limit_ttl+\",\\n\")\r\n"
				+ "			.append(\"RawDocsSearchTime: \").append(RawDocsSearchTime+\",\\n\")\r\n"
				+ "			.append(\"quota: \").append(quota+\",\\n\")\r\n"
				+ "			.append(\"limit: \").append(limit+\",\\n\")\r\n"
				+ "			.append(\"ReRankSearchTime: \").append(ReRankSearchTime+\",\\n\")\r\n"
				+ "			.append(\"quota_ttl: \").append(quota_ttl+\",\\n\")\r\n"
				+ "			.append(\"trial: \").append(trial+\",\\n\")\r\n"
				+ "			.append(\"\\n}\").toString();\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public static class Builder {\r\n"
				+ "		public int RawDocsCount;\r\n"
				+ "		public boolean CacheHit;\r\n"
				+ "		public String[] strings;\r\n"
				+ "		public Doc[] docs;\r\n"
				+ "		public int limit_ttl;\r\n"
				+ "		public int RawDocsSearchTime;\r\n"
				+ "		public int quota;\r\n"
				+ "		public int limit;\r\n"
				+ "		public int ReRankSearchTime;\r\n"
				+ "		public int quota_ttl;\r\n"
				+ "		public int trial;\r\n"
				+ "\r\n"
				+ "		public Builder setRawDocsCount(int RawDocsCount) {\r\n"
				+ "			this.RawDocsCount = RawDocsCount;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setCacheHit(boolean CacheHit) {\r\n"
				+ "			this.CacheHit = CacheHit;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setStrings(String[] strings) {\r\n"
				+ "			this.strings = strings;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setDocs(Doc[] docs) {\r\n"
				+ "			this.docs = docs;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setLimit_ttl(int limit_ttl) {\r\n"
				+ "			this.limit_ttl = limit_ttl;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setRawDocsSearchTime(int RawDocsSearchTime) {\r\n"
				+ "			this.RawDocsSearchTime = RawDocsSearchTime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setQuota(int quota) {\r\n"
				+ "			this.quota = quota;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setLimit(int limit) {\r\n"
				+ "			this.limit = limit;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setReRankSearchTime(int ReRankSearchTime) {\r\n"
				+ "			this.ReRankSearchTime = ReRankSearchTime;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setQuota_ttl(int quota_ttl) {\r\n"
				+ "			this.quota_ttl = quota_ttl;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Builder setTrial(int trial) {\r\n"
				+ "			this.trial = trial;\r\n"
				+ "			return this;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public AnimeResult build() {\r\n"
				+ "			return new AnimeResult(RawDocsCount,CacheHit,strings,docs,limit_ttl,RawDocsSearchTime,quota,limit,ReRankSearchTime,quota_ttl,trial);\r\n"
				+ "		}\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "	public static final class Doc implements Serializable {\r\n"
				+ "		private static final long serialVersionUID = 1L;\r\n"
				+ "		public String title_chinese;\r\n"
				+ "		public String title_native;\r\n"
				+ "		public String[] synonyms;\r\n"
				+ "		public String title_romaji;\r\n"
				+ "		public int episode;\r\n"
				+ "		public int mal_id;\r\n"
				+ "		public String title;\r\n"
				+ "		public int anilist_id;\r\n"
				+ "		public boolean is_adult;\r\n"
				+ "		public String tokenthumb;\r\n"
				+ "		public Synonyms_chinese[] synonyms_chinese;\r\n"
				+ "		public double at;\r\n"
				+ "		public String filename;\r\n"
				+ "		public double similarity;\r\n"
				+ "		public String season;\r\n"
				+ "		public String title_english;\r\n"
				+ "		public double from;\r\n"
				+ "		public double to;\r\n"
				+ "		public String anime;\r\n"
				+ "\r\n"
				+ "		public Doc(String title_chinese, String title_native, String[] synonyms, String title_romaji, int episode, int mal_id, String title, int anilist_id, boolean is_adult, String tokenthumb, Synonyms_chinese[] synonyms_chinese, double at, String filename, double similarity, String season, String title_english, double from, double to, String anime) {\r\n"
				+ "			this.title_chinese = title_chinese;\r\n"
				+ "			this.title_native = title_native;\r\n"
				+ "			this.synonyms = synonyms;\r\n"
				+ "			this.title_romaji = title_romaji;\r\n"
				+ "			this.episode = episode;\r\n"
				+ "			this.mal_id = mal_id;\r\n"
				+ "			this.title = title;\r\n"
				+ "			this.anilist_id = anilist_id;\r\n"
				+ "			this.is_adult = is_adult;\r\n"
				+ "			this.tokenthumb = tokenthumb;\r\n"
				+ "			this.synonyms_chinese = synonyms_chinese;\r\n"
				+ "			this.at = at;\r\n"
				+ "			this.filename = filename;\r\n"
				+ "			this.similarity = similarity;\r\n"
				+ "			this.season = season;\r\n"
				+ "			this.title_english = title_english;\r\n"
				+ "			this.from = from;\r\n"
				+ "			this.to = to;\r\n"
				+ "			this.anime = anime;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getTitle_chinese() {\r\n"
				+ "			return title_chinese;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getTitle_native() {\r\n"
				+ "			return title_native;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String[] getSynonyms() {\r\n"
				+ "			return synonyms;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getTitle_romaji() {\r\n"
				+ "			return title_romaji;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public int getEpisode() {\r\n"
				+ "			return episode;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public int getMal_id() {\r\n"
				+ "			return mal_id;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getTitle() {\r\n"
				+ "			return title;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public int getAnilist_id() {\r\n"
				+ "			return anilist_id;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public boolean getIs_adult() {\r\n"
				+ "			return is_adult;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getTokenthumb() {\r\n"
				+ "			return tokenthumb;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public Synonyms_chinese[] getSynonyms_chinese() {\r\n"
				+ "			return synonyms_chinese;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public double getAt() {\r\n"
				+ "			return at;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getFilename() {\r\n"
				+ "			return filename;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public double getSimilarity() {\r\n"
				+ "			return similarity;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getSeason() {\r\n"
				+ "			return season;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getTitle_english() {\r\n"
				+ "			return title_english;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public double getFrom() {\r\n"
				+ "			return from;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public double getTo() {\r\n"
				+ "			return to;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public String getAnime() {\r\n"
				+ "			return anime;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTitle_chinese(String title_chinese) {\r\n"
				+ "			this.title_chinese = title_chinese;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTitle_native(String title_native) {\r\n"
				+ "			this.title_native = title_native;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setSynonyms(String[] synonyms) {\r\n"
				+ "			this.synonyms = synonyms;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTitle_romaji(String title_romaji) {\r\n"
				+ "			this.title_romaji = title_romaji;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setEpisode(int episode) {\r\n"
				+ "			this.episode = episode;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setMal_id(int mal_id) {\r\n"
				+ "			this.mal_id = mal_id;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTitle(String title) {\r\n"
				+ "			this.title = title;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setAnilist_id(int anilist_id) {\r\n"
				+ "			this.anilist_id = anilist_id;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setIs_adult(boolean is_adult) {\r\n"
				+ "			this.is_adult = is_adult;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTokenthumb(String tokenthumb) {\r\n"
				+ "			this.tokenthumb = tokenthumb;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setSynonyms_chinese(Synonyms_chinese[] synonyms_chinese) {\r\n"
				+ "			this.synonyms_chinese = synonyms_chinese;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setAt(double at) {\r\n"
				+ "			this.at = at;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setFilename(String filename) {\r\n"
				+ "			this.filename = filename;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setSimilarity(double similarity) {\r\n"
				+ "			this.similarity = similarity;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setSeason(String season) {\r\n"
				+ "			this.season = season;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTitle_english(String title_english) {\r\n"
				+ "			this.title_english = title_english;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setFrom(double from) {\r\n"
				+ "			this.from = from;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setTo(double to) {\r\n"
				+ "			this.to = to;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public void setAnime(String anime) {\r\n"
				+ "			this.anime = anime;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		@Override\r\n"
				+ "		public String toString() {\r\n"
				+ "			return new StringBuilder()\r\n"
				+ "				.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "				.append(\"title_chinese: \").append(title_chinese+\",\\n\")\r\n"
				+ "				.append(\"title_native: \").append(title_native+\",\\n\")\r\n"
				+ "				.append(\"synonyms: \").append(synonyms+\",\\n\")\r\n"
				+ "				.append(\"title_romaji: \").append(title_romaji+\",\\n\")\r\n"
				+ "				.append(\"episode: \").append(episode+\",\\n\")\r\n"
				+ "				.append(\"mal_id: \").append(mal_id+\",\\n\")\r\n"
				+ "				.append(\"title: \").append(title+\",\\n\")\r\n"
				+ "				.append(\"anilist_id: \").append(anilist_id+\",\\n\")\r\n"
				+ "				.append(\"is_adult: \").append(is_adult+\",\\n\")\r\n"
				+ "				.append(\"tokenthumb: \").append(tokenthumb+\",\\n\")\r\n"
				+ "				.append(\"synonyms_chinese: \").append(synonyms_chinese+\",\\n\")\r\n"
				+ "				.append(\"at: \").append(at+\",\\n\")\r\n"
				+ "				.append(\"filename: \").append(filename+\",\\n\")\r\n"
				+ "				.append(\"similarity: \").append(similarity+\",\\n\")\r\n"
				+ "				.append(\"season: \").append(season+\",\\n\")\r\n"
				+ "				.append(\"title_english: \").append(title_english+\",\\n\")\r\n"
				+ "				.append(\"from: \").append(from+\",\\n\")\r\n"
				+ "				.append(\"to: \").append(to+\",\\n\")\r\n"
				+ "				.append(\"anime: \").append(anime+\",\\n\")\r\n"
				+ "				.append(\"\\n}\").toString();\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public static class Builder {\r\n"
				+ "			public String title_chinese;\r\n"
				+ "			public String title_native;\r\n"
				+ "			public String[] synonyms;\r\n"
				+ "			public String title_romaji;\r\n"
				+ "			public int episode;\r\n"
				+ "			public int mal_id;\r\n"
				+ "			public String title;\r\n"
				+ "			public int anilist_id;\r\n"
				+ "			public boolean is_adult;\r\n"
				+ "			public String tokenthumb;\r\n"
				+ "			public Synonyms_chinese[] synonyms_chinese;\r\n"
				+ "			public double at;\r\n"
				+ "			public String filename;\r\n"
				+ "			public double similarity;\r\n"
				+ "			public String season;\r\n"
				+ "			public String title_english;\r\n"
				+ "			public double from;\r\n"
				+ "			public double to;\r\n"
				+ "			public String anime;\r\n"
				+ "\r\n"
				+ "			public Builder setTitle_chinese(String title_chinese) {\r\n"
				+ "				this.title_chinese = title_chinese;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setTitle_native(String title_native) {\r\n"
				+ "				this.title_native = title_native;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setSynonyms(String[] synonyms) {\r\n"
				+ "				this.synonyms = synonyms;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setTitle_romaji(String title_romaji) {\r\n"
				+ "				this.title_romaji = title_romaji;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setEpisode(int episode) {\r\n"
				+ "				this.episode = episode;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setMal_id(int mal_id) {\r\n"
				+ "				this.mal_id = mal_id;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setTitle(String title) {\r\n"
				+ "				this.title = title;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setAnilist_id(int anilist_id) {\r\n"
				+ "				this.anilist_id = anilist_id;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setIs_adult(boolean is_adult) {\r\n"
				+ "				this.is_adult = is_adult;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setTokenthumb(String tokenthumb) {\r\n"
				+ "				this.tokenthumb = tokenthumb;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setSynonyms_chinese(Synonyms_chinese[] synonyms_chinese) {\r\n"
				+ "				this.synonyms_chinese = synonyms_chinese;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setAt(double at) {\r\n"
				+ "				this.at = at;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setFilename(String filename) {\r\n"
				+ "				this.filename = filename;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setSimilarity(double similarity) {\r\n"
				+ "				this.similarity = similarity;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setSeason(String season) {\r\n"
				+ "				this.season = season;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setTitle_english(String title_english) {\r\n"
				+ "				this.title_english = title_english;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setFrom(double from) {\r\n"
				+ "				this.from = from;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setTo(double to) {\r\n"
				+ "				this.to = to;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Builder setAnime(String anime) {\r\n"
				+ "				this.anime = anime;\r\n"
				+ "				return this;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Doc build() {\r\n"
				+ "				return new Doc(title_chinese,title_native,synonyms,title_romaji,episode,mal_id,title,anilist_id,is_adult,tokenthumb,synonyms_chinese,at,filename,similarity,season,title_english,from,to,anime);\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		public static final class Synonyms_chinese implements Serializable {\r\n"
				+ "			private static final long serialVersionUID = 1L;\r\n"
				+ "			public Object empty;\r\n"
				+ "\r\n"
				+ "			public Synonyms_chinese(Object empty) {\r\n"
				+ "				this.empty = empty;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public Object getEmpty() {\r\n"
				+ "				return empty;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public void setEmpty(Object empty) {\r\n"
				+ "				this.empty = empty;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			@Override\r\n"
				+ "			public String toString() {\r\n"
				+ "				return new StringBuilder()\r\n"
				+ "					.append(getClass().getName()).append(\"{\\n\")\r\n"
				+ "					.append(\"empty: \").append(empty+\",\\n\")\r\n"
				+ "					.append(\"\\n}\").toString();\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			public static class Builder {\r\n"
				+ "				public Object empty;\r\n"
				+ "\r\n"
				+ "				public Builder setEmpty(Object empty) {\r\n"
				+ "					this.empty = empty;\r\n"
				+ "					return this;\r\n"
				+ "				}\r\n"
				+ "\r\n"
				+ "				public Synonyms_chinese build() {\r\n"
				+ "					return new Synonyms_chinese(empty);\r\n"
				+ "				}\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "	}\r\n"
				+ "\r\n"
				+ "}";
}