package tests.lib;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Scanner;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import json.interpreter.JsonGenerator;
import lib.HTTP.RequestBuilder;
import lib.HTTP.ResponseHandler;

public class TestJsonGenerator {

	@Tag("slow")
    @Test
    public void generateJsonFromRequest() throws Exception {
		try (
			RequestBuilder builder = new RequestBuilder("https://api.bintray.com/packages/sedmelluq/com.sedmelluq/jda-nas/");
			ResponseHandler handler = new ResponseHandler(builder.build());
		) {
	        JsonGenerator generator = new JsonGenerator("NASResult", handler.getResponse());
	        String result = trimTrailing(generator.interpret().toString());
	        assertEquals(Constants.JSON_OUT_NAS, result);
		}
    }
	
	public static String trimTrailing(String input) {
		StringBuilder sb = new StringBuilder();
		try (Scanner sc = new Scanner(input.trim())) {
			while (sc.hasNextLine()) 
				sb.append(sc.nextLine() + System.lineSeparator());
			return sb.toString();
		}
	}
}

final class Constants {
	public static final String JSON_OUT_NAS = TestJsonGenerator.trimTrailing("import java.io.Serializable;\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "public final class NASResult implements Serializable {\r\n"
			+ "	private static final long serialVersionUID = 1L;\r\n"
			+ "	public String owner;\r\n"
			+ "	public String[] attribute_names;\r\n"
			+ "	public String[] custom_licenses;\r\n"
			+ "	public String maturity;\r\n"
			+ "	public String created;\r\n"
			+ "	public String vcs_url;\r\n"
			+ "	public String repo;\r\n"
			+ "	public String[] labels;\r\n"
			+ "	public int rating_count;\r\n"
			+ "	public String[] linked_to_repos;\r\n"
			+ "	public String[] licenses;\r\n"
			+ "	public String website_url;\r\n"
			+ "	public String latest_version;\r\n"
			+ "	public String[] versions;\r\n"
			+ "	public String[] permissions;\r\n"
			+ "	public int followers_count;\r\n"
			+ "	public String name;\r\n"
			+ "	public String updated;\r\n"
			+ "	public String[] system_ids;\r\n"
			+ "	public String desc;\r\n"
			+ "	public String issue_tracker_url;\r\n"
			+ "\r\n"
			+ "	public NASResult(String owner, String[] attribute_names, String[] custom_licenses, String maturity, String created, String vcs_url, String repo, String[] labels, int rating_count, String[] linked_to_repos, String[] licenses, String website_url, String latest_version, String[] versions, String[] permissions, int followers_count, String name, String updated, String[] system_ids, String desc, String issue_tracker_url) {\r\n"
			+ "		this.owner = owner;\r\n"
			+ "		this.attribute_names = attribute_names;\r\n"
			+ "		this.custom_licenses = custom_licenses;\r\n"
			+ "		this.maturity = maturity;\r\n"
			+ "		this.created = created;\r\n"
			+ "		this.vcs_url = vcs_url;\r\n"
			+ "		this.repo = repo;\r\n"
			+ "		this.labels = labels;\r\n"
			+ "		this.rating_count = rating_count;\r\n"
			+ "		this.linked_to_repos = linked_to_repos;\r\n"
			+ "		this.licenses = licenses;\r\n"
			+ "		this.website_url = website_url;\r\n"
			+ "		this.latest_version = latest_version;\r\n"
			+ "		this.versions = versions;\r\n"
			+ "		this.permissions = permissions;\r\n"
			+ "		this.followers_count = followers_count;\r\n"
			+ "		this.name = name;\r\n"
			+ "		this.updated = updated;\r\n"
			+ "		this.system_ids = system_ids;\r\n"
			+ "		this.desc = desc;\r\n"
			+ "		this.issue_tracker_url = issue_tracker_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getOwner() {\r\n"
			+ "		return owner;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getAttribute_names() {\r\n"
			+ "		return attribute_names;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getCustom_licenses() {\r\n"
			+ "		return custom_licenses;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getMaturity() {\r\n"
			+ "		return maturity;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getCreated() {\r\n"
			+ "		return created;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getVcs_url() {\r\n"
			+ "		return vcs_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getRepo() {\r\n"
			+ "		return repo;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getLabels() {\r\n"
			+ "		return labels;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public int getRating_count() {\r\n"
			+ "		return rating_count;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getLinked_to_repos() {\r\n"
			+ "		return linked_to_repos;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getLicenses() {\r\n"
			+ "		return licenses;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getWebsite_url() {\r\n"
			+ "		return website_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getLatest_version() {\r\n"
			+ "		return latest_version;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getVersions() {\r\n"
			+ "		return versions;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getPermissions() {\r\n"
			+ "		return permissions;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public int getFollowers_count() {\r\n"
			+ "		return followers_count;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getName() {\r\n"
			+ "		return name;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getUpdated() {\r\n"
			+ "		return updated;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String[] getSystem_ids() {\r\n"
			+ "		return system_ids;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getDesc() {\r\n"
			+ "		return desc;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public String getIssue_tracker_url() {\r\n"
			+ "		return issue_tracker_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setOwner(String owner) {\r\n"
			+ "		this.owner = owner;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setAttribute_names(String[] attribute_names) {\r\n"
			+ "		this.attribute_names = attribute_names;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setCustom_licenses(String[] custom_licenses) {\r\n"
			+ "		this.custom_licenses = custom_licenses;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setMaturity(String maturity) {\r\n"
			+ "		this.maturity = maturity;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setCreated(String created) {\r\n"
			+ "		this.created = created;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setVcs_url(String vcs_url) {\r\n"
			+ "		this.vcs_url = vcs_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setRepo(String repo) {\r\n"
			+ "		this.repo = repo;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setLabels(String[] labels) {\r\n"
			+ "		this.labels = labels;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setRating_count(int rating_count) {\r\n"
			+ "		this.rating_count = rating_count;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setLinked_to_repos(String[] linked_to_repos) {\r\n"
			+ "		this.linked_to_repos = linked_to_repos;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setLicenses(String[] licenses) {\r\n"
			+ "		this.licenses = licenses;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setWebsite_url(String website_url) {\r\n"
			+ "		this.website_url = website_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setLatest_version(String latest_version) {\r\n"
			+ "		this.latest_version = latest_version;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setVersions(String[] versions) {\r\n"
			+ "		this.versions = versions;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setPermissions(String[] permissions) {\r\n"
			+ "		this.permissions = permissions;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setFollowers_count(int followers_count) {\r\n"
			+ "		this.followers_count = followers_count;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setName(String name) {\r\n"
			+ "		this.name = name;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setUpdated(String updated) {\r\n"
			+ "		this.updated = updated;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setSystem_ids(String[] system_ids) {\r\n"
			+ "		this.system_ids = system_ids;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setDesc(String desc) {\r\n"
			+ "		this.desc = desc;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public void setIssue_tracker_url(String issue_tracker_url) {\r\n"
			+ "		this.issue_tracker_url = issue_tracker_url;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	@Override\r\n"
			+ "	public String toString() {\r\n"
			+ "		return new StringBuilder()\r\n"
			+ "			.append(getClass().getName()).append(\"{\\n\")\r\n"
			+ "			.append(\"owner: \").append(owner+\",\\n\")\r\n"
			+ "			.append(\"attribute_names: \").append(attribute_names+\",\\n\")\r\n"
			+ "			.append(\"custom_licenses: \").append(custom_licenses+\",\\n\")\r\n"
			+ "			.append(\"maturity: \").append(maturity+\",\\n\")\r\n"
			+ "			.append(\"created: \").append(created+\",\\n\")\r\n"
			+ "			.append(\"vcs_url: \").append(vcs_url+\",\\n\")\r\n"
			+ "			.append(\"repo: \").append(repo+\",\\n\")\r\n"
			+ "			.append(\"labels: \").append(labels+\",\\n\")\r\n"
			+ "			.append(\"rating_count: \").append(rating_count+\",\\n\")\r\n"
			+ "			.append(\"linked_to_repos: \").append(linked_to_repos+\",\\n\")\r\n"
			+ "			.append(\"licenses: \").append(licenses+\",\\n\")\r\n"
			+ "			.append(\"website_url: \").append(website_url+\",\\n\")\r\n"
			+ "			.append(\"latest_version: \").append(latest_version+\",\\n\")\r\n"
			+ "			.append(\"versions: \").append(versions+\",\\n\")\r\n"
			+ "			.append(\"permissions: \").append(permissions+\",\\n\")\r\n"
			+ "			.append(\"followers_count: \").append(followers_count+\",\\n\")\r\n"
			+ "			.append(\"name: \").append(name+\",\\n\")\r\n"
			+ "			.append(\"updated: \").append(updated+\",\\n\")\r\n"
			+ "			.append(\"system_ids: \").append(system_ids+\",\\n\")\r\n"
			+ "			.append(\"desc: \").append(desc+\",\\n\")\r\n"
			+ "			.append(\"issue_tracker_url: \").append(issue_tracker_url+\",\\n\")\r\n"
			+ "			.append(\"\\n}\").toString();\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	public static class Builder {\r\n"
			+ "		public String owner;\r\n"
			+ "		public String[] attribute_names;\r\n"
			+ "		public String[] custom_licenses;\r\n"
			+ "		public String maturity;\r\n"
			+ "		public String created;\r\n"
			+ "		public String vcs_url;\r\n"
			+ "		public String repo;\r\n"
			+ "		public String[] labels;\r\n"
			+ "		public int rating_count;\r\n"
			+ "		public String[] linked_to_repos;\r\n"
			+ "		public String[] licenses;\r\n"
			+ "		public String website_url;\r\n"
			+ "		public String latest_version;\r\n"
			+ "		public String[] versions;\r\n"
			+ "		public String[] permissions;\r\n"
			+ "		public int followers_count;\r\n"
			+ "		public String name;\r\n"
			+ "		public String updated;\r\n"
			+ "		public String[] system_ids;\r\n"
			+ "		public String desc;\r\n"
			+ "		public String issue_tracker_url;\r\n"
			+ "\r\n"
			+ "		public Builder setOwner(String owner) {\r\n"
			+ "			this.owner = owner;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setAttribute_names(String[] attribute_names) {\r\n"
			+ "			this.attribute_names = attribute_names;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setCustom_licenses(String[] custom_licenses) {\r\n"
			+ "			this.custom_licenses = custom_licenses;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setMaturity(String maturity) {\r\n"
			+ "			this.maturity = maturity;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setCreated(String created) {\r\n"
			+ "			this.created = created;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setVcs_url(String vcs_url) {\r\n"
			+ "			this.vcs_url = vcs_url;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setRepo(String repo) {\r\n"
			+ "			this.repo = repo;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setLabels(String[] labels) {\r\n"
			+ "			this.labels = labels;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setRating_count(int rating_count) {\r\n"
			+ "			this.rating_count = rating_count;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setLinked_to_repos(String[] linked_to_repos) {\r\n"
			+ "			this.linked_to_repos = linked_to_repos;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setLicenses(String[] licenses) {\r\n"
			+ "			this.licenses = licenses;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setWebsite_url(String website_url) {\r\n"
			+ "			this.website_url = website_url;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setLatest_version(String latest_version) {\r\n"
			+ "			this.latest_version = latest_version;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setVersions(String[] versions) {\r\n"
			+ "			this.versions = versions;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setPermissions(String[] permissions) {\r\n"
			+ "			this.permissions = permissions;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setFollowers_count(int followers_count) {\r\n"
			+ "			this.followers_count = followers_count;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setName(String name) {\r\n"
			+ "			this.name = name;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setUpdated(String updated) {\r\n"
			+ "			this.updated = updated;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setSystem_ids(String[] system_ids) {\r\n"
			+ "			this.system_ids = system_ids;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setDesc(String desc) {\r\n"
			+ "			this.desc = desc;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public Builder setIssue_tracker_url(String issue_tracker_url) {\r\n"
			+ "			this.issue_tracker_url = issue_tracker_url;\r\n"
			+ "			return this;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "		public NASResult build() {\r\n"
			+ "			return new NASResult(owner,attribute_names,custom_licenses,maturity,created,vcs_url,repo,labels,rating_count,linked_to_repos,licenses,website_url,latest_version,versions,permissions,followers_count,name,updated,system_ids,desc,issue_tracker_url);\r\n"
			+ "		}\r\n"
			+ "	}\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "\r\n"
			+ ""
		);
}